version: '3.8'

services:
  backend:
    build: ./backend
    container_name: employees_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdb
      DB_PORT: 5432
    restart: always
    networks:
      - mainapp_net

  frontend:
    build: ./frontend
    container_name: employees_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - mainapp_net

  db:
    image: postgres:latest
    container_name: employees_db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/dataa659a866d885
    networks:
      - mainapp_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d yourdb"]
      interval: 10s
      retries: 5
      
networks:
  mainapp_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
